"""Add mode to conversations and create message_feedback table

Revision ID: 24c3182d5fb8
Revises: ae056b363b7c
Create Date: 2025-12-18 09:49:11.844006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24c3182d5fb8'
down_revision: Union[str, None] = 'ae056b363b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_feedback',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feedback_type', sa.Enum('upvote', 'downvote', 'download', name='feedbacktype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_feedback_created_at'), 'message_feedback', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_feedback_message_id'), 'message_feedback', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_feedback_user_id'), 'message_feedback', ['user_id'], unique=False)
    op.alter_column('api_usage', 'calls',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_usage', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_usage', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('api_usage', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('api_usage', 'models_used',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.add_column('conversations', sa.Column('mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'mode')
    op.alter_column('api_usage', 'models_used',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('api_usage', 'cost_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('api_usage', 'total_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('api_usage', 'completion_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('api_usage', 'prompt_tokens',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('api_usage', 'calls',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_message_feedback_user_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_message_id'), table_name='message_feedback')
    op.drop_index(op.f('ix_message_feedback_created_at'), table_name='message_feedback')
    op.drop_table('message_feedback')
    # ### end Alembic commands ###
